- name: conditions
  hosts: local
  connection: local
  vars:
    my_number: 15
  tasks:
    - name: checking the given number
      ansible.builtin.debug:
        msg: "given number {{ my_number }} is greater than 10"
      when: my_number > 10
    - name: checking the given number 
      ansible.builtin.debug:
        msg: "given number {{ my_number }} is greater than are equal to 10"
      when: my_number >= 10