- name: installing nginx
  hosts: local
  become: yes
  tasks:
  - name: Now going to Installing nginx
    anisble.builtin.package:
      name: nginx
      state: present
  - name: started nginx
    ansible.builtin.service:
      name: nginx
      state: started