- name: packages with installing loop
  hosts: web
  become: yes
  tasks:
  - name: loops with installing packages
    ansible.builtin.packages:
      name: "{{ item }}"
      state: present
    loops:
      - gcc
      - java
      - mysql