- name: Command vs shell
  hosts: web
  become: yes
  tasks:
  - name: command vs shell
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
  - name: command vs shell
    ansible.builtin.command: ls -ltr
    register: command_result
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ command_result }}"

  