- name: vars in prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: COURSE
      prompt: please enter the course:
    - name: DURATION
      prompt: please enter the duration:
  tasks:
  - name: vars in prompt
    ansible.builtin.debug:
      msg: "i'm learning devops {{ COURSE }} and the course duration is {{ DURATION }}"
