- name: varibale s from file
  hosts: local
  connection: local
  vars_files:
  - file.yaml
  tasks:  
  - name: vars in fails
    ansible.builtin.debug:
      msg: "I'm learning {{ COURSE }} and the duration in {{ DURATION }}"