- name: data types
  hosts: local
  connection: local
  vars:
    Course: "learning aws devops"
    Duration: 120
    tools:
      - aws
      - jenkins
      - anmsible
      - shell script
    live: true
    topics:
      cicd: jenkins
      automate: shell script
      configuration: Ansible
  tasks:
  - name: print course
    ansible.builtin.debug:
      msg: "I'm learning the {{ Course }} and it's duration is {{ Duration }} and tool are {{ tools }} and it is live {{ live }} and the topics are {{ topics }}"
  
    